// End-to-end forward pass: decode/prefill of the full 24-layer model against
// golden logits from mlx-lm (tests/data/logits_reference.json, generated by
// tests/reference/gen_logits_reference.py), determinism, and long-context
// (sliding window wrap-around) sanity.
#include "test.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "coral/gpu.h"
#include "coral/json.h"
#include "coral/model.h"
#include "coral/tokenizer.h"

using namespace coral;

// Shared with test_gemv.cpp / test_attention.cpp (one model load per binary).
gpu::Device& attn_test_device();
Model& attn_test_model();

// Shared with test_engine.cpp.
std::shared_ptr<Tokenizer> forward_test_tokenizer() {
    std::string dir = test::model_dir_or_skip();
    static std::shared_ptr<Tokenizer> t = Tokenizer::load(dir);
    return t;
}

namespace {

struct Run {
    std::vector<float> logits;       // last prompt position
    std::vector<int32_t> greedy;     // greedy continuation (first = argmax of `logits`)
};

// Prefill `tokens`, copy the last logits, then continue greedily for `n` tokens.
Run run_greedy(const std::vector<int32_t>& tokens, uint32_t n, ForwardStats* stats = nullptr) {
    auto& dev = attn_test_device();
    Model& m = attn_test_model();
    auto cs = dev.stream();
    KVCache cache = m.new_cache(uint32_t(tokens.size()) + n + 8);
    gpu::Buffer logits;
    Run r;
    int32_t tok = m.prefill_argmax(cs, cache, tokens, logits, stats);
    r.logits.assign(logits.as<float>(), logits.as<float>() + m.config().vocab_size);
    CHECK_EQ(cache.length, uint32_t(tokens.size()));
    for (uint32_t i = 0; i < n; ++i) {
        r.greedy.push_back(tok);
        if (i + 1 < n) tok = m.decode_argmax(cs, cache, tok, logits, stats);
    }
    return r;
}

int32_t cpu_argmax(const std::vector<float>& v) {
    return int32_t(std::max_element(v.begin(), v.end()) - v.begin());
}

} // namespace

CORAL_TEST(forward_matches_mlx_reference) {
    const std::string path = "tests/data/logits_reference.json";
    if (!std::filesystem::exists(path)) SKIP("tests/data/logits_reference.json absent (run tests/reference/gen_logits_reference.py)");
    Model& m = attn_test_model();
    std::ifstream f(path);
    std::stringstream ss;
    ss << f.rdbuf();
    const Json ref = Json::parse(ss.str());
    const auto& cases = ref["cases"].as_array();
    CHECK(!cases.empty());
    bool ok = true;
    size_t tight_cases = 0;
    for (const Json& c : cases) {
        std::vector<int32_t> tokens;
        for (const Json& t : c["tokens"].as_array()) tokens.push_back(int32_t(t.as_int()));
        std::vector<int32_t> ref_cont;
        for (const Json& t : c["greedy_continuation"].as_array()) ref_cont.push_back(int32_t(t.as_int()));
        const int32_t ref_argmax = int32_t(c["argmax"].as_int());

        ForwardStats st;
        const Run r = run_greedy(tokens, uint32_t(ref_cont.size()), &st);
        const auto& L = r.logits;
        CHECK_EQ(L.size(), size_t(m.config().vocab_size));

        // GPU argmax agrees with the CPU argmax of the same logits.
        CHECK_EQ(r.greedy[0], cpu_argmax(L));

        // Our top-3.
        std::vector<int32_t> idx(L.size());
        for (size_t i = 0; i < idx.size(); ++i) idx[i] = int32_t(i);
        std::partial_sort(idx.begin(), idx.begin() + 3, idx.end(), [&](int32_t a, int32_t b) { return L[a] > L[b]; });

        // Pearson correlation and max |diff| over the reference's top-64 ids.
        double sx = 0, sy = 0, sxx = 0, syy = 0, sxy = 0, maxd = 0;
        size_t n = 0;
        for (const Json& e : c["top_logits"].as_array()) {
            const double x = L.at(size_t(e[0].as_int())), y = e[1].as_double();
            sx += x; sy += y; sxx += x * x; syy += y * y; sxy += x * y; ++n;
            maxd = std::max(maxd, std::fabs(x - y));
        }
        const double cov = sxy / n - (sx / n) * (sy / n);
        const double corr = cov / std::sqrt((sxx / n - (sx / n) * (sx / n)) * (syy / n - (sy / n) * (sy / n)));

        double mean = 0, var = 0;
        for (float v : L) mean += v;
        mean /= L.size();
        for (float v : L) var += (v - mean) * (v - mean);
        const double sd = std::sqrt(var / L.size());

        size_t prefix = 0, total = 0;
        while (prefix < ref_cont.size() && r.greedy[prefix] == ref_cont[prefix]) ++prefix;
        for (size_t i = 0; i < ref_cont.size(); ++i) total += r.greedy[i] == ref_cont[i];

        std::string name = c["name"].as_string();
        for (char& ch : name) if (ch == '\n') ch = ' ';
        std::printf("        [%s] %zu tok: argmax %d (ref %d, logit %.3f vs %.3f) top3 {%d,%d,%d} "
                    "corr(top64) %.5f max|d| %.3f mean %.3f/%.3f std %.3f/%.3f greedy prefix %zu/%zu (same %zu)  "
                    "%.1f ms/tok gpu\n",
                    name.c_str(), tokens.size(), r.greedy[0], ref_argmax, L[ref_argmax],
                    c["top_logits"][0][1].as_double(), idx[0], idx[1], idx[2], corr, maxd, mean,
                    c["logit_mean"].as_double(), sd, c["logit_std"].as_double(), prefix, ref_cont.size(), total,
                    st.gpu_seconds * 1e3 / st.tokens);

        if (const char* d = std::getenv("CORAL_DUMP_LOGITS")) {   // dev aid: raw fp32 last-position logits
            std::ofstream o(std::string(d) + "/" + std::to_string(&c - cases.data()) + ".f32", std::ios::binary);
            o.write(reinterpret_cast<const char*>(L.data()), std::streamsize(L.size() * 4));
        }
        if (std::getenv("CORAL_DUMP_TOP")) {
            for (const Json& e : c["top_logits"].as_array())
                std::printf("          %6lld ref %8.4f ours %8.4f d %+.3f\n", (long long)e[0].as_int(),
                            e[1].as_double(), L[size_t(e[0].as_int())], L[size_t(e[0].as_int())] - e[1].as_double());
        }
        ok = ok && r.greedy[0] == ref_argmax;
        ok = ok && std::find(idx.begin(), idx.begin() + 3, ref_argmax) != idx.begin() + 3;
        // The reference is mlx-lm with fp32 attention/embeddings/activations
        // (MXFP4 experts). Two bars:
        //   loose (every case): corr(top-64) > 0.98 and argmax + top-3 agree.
        //   tight (>= 2/3 of cases): corr > 0.995 and >= 8 greedy tokens match.
        // A discrete routing near-tie can legitimately break the tight bar for
        // one prompt: "The capital of France is" has a layer-0 router tie on
        // " capital" (4th vs 5th expert logit 0.7885 vs 0.7848); our bf16 KV
        // cache flips it and the continuation diverges after the first token,
        // while corr stays 0.986. A systemic bug fails the tight bar everywhere.
        ok = ok && corr > 0.98;
        const bool tight = corr > 0.995 && prefix >= std::min<size_t>(8, ref_cont.size());
        if (tight) ++tight_cases;
        std::printf("          -> %s\n", tight ? "tight" : "loose (near-tie or precision)");
    }
    ok = ok && tight_cases * 3 >= cases.size() * 2;   // at least two thirds of the cases pass the tight bar
    CHECK(ok);
}

CORAL_TEST(forward_deterministic) {
    const std::vector<int32_t> prompt = {976, 9029, 328, 10128, 382};   // "The capital of France is"
    const Run a = run_greedy(prompt, 16), b = run_greedy(prompt, 16);
    CHECK(a.greedy == b.greedy);
    CHECK(a.logits == b.logits);   // bitwise
}

CORAL_TEST(forward_long_context_sliding_window) {
    auto tok = forward_test_tokenizer();
    std::string text;
    for (int i = 0; i < 30; ++i)
        text += "The quick brown fox jumps over the lazy dog near the river bank. ";
    text += "After that, the fox";
    const std::vector<int32_t> prompt = tok->encode(text);
    CHECK(prompt.size() > 256);   // > 2 sliding windows: the ring buffer wraps
    ForwardStats st;
    const Run r = run_greedy(prompt, 32, &st);
    const std::string out = tok->decode(r.greedy);
    std::printf("        %zu prompt tokens, prefill+decode %.1f ms/tok gpu, %u submits; continuation: \"%s\"\n",
                prompt.size(), st.gpu_seconds * 1e3 / st.tokens, st.submits, out.c_str());
    for (float v : r.logits) CHECK(std::isfinite(v));
    size_t run = 1, longest = 1;
    for (size_t i = 1; i < r.greedy.size(); ++i) {
        run = r.greedy[i] == r.greedy[i - 1] ? run + 1 : 1;
        longest = std::max(longest, run);
    }
    CHECK(longest < 16);
    // Not degenerate: several distinct tokens.
    std::vector<int32_t> u = r.greedy;
    std::sort(u.begin(), u.end());
    CHECK(std::unique(u.begin(), u.end()) - u.begin() >= 4);
}

CORAL_TEST(forward_encode_only_argmax) {
    // encode_decode with only an argmax output (no caller logits), several
    // tokens in one command buffer, matches the synchronous path.
    auto& dev = attn_test_device();
    Model& m = attn_test_model();
    const std::vector<int32_t> prompt = {976, 9029, 328, 10128, 382};
    const Run ref = run_greedy(prompt, 1);
    auto cs = dev.stream();
    KVCache cache = m.new_cache(64);
    gpu::Buffer am;
    cs.begin();
    for (size_t i = 0; i < prompt.size(); ++i)
        m.encode_decode(cs, cache, prompt[i], nullptr, i + 1 == prompt.size() ? &am : nullptr);
    const size_t d = cs.dispatch_count();
    cs.submit_and_wait();
    std::printf("        %zu dispatches for %zu tokens (%zu/token + 3 for lm_head+argmax)\n", d, prompt.size(),
                (d - 3) / prompt.size());
    CHECK_EQ(am.as<int32_t>()[0], ref.greedy[0]);
    CHECK_EQ(cache.length, uint32_t(prompt.size()));
    // Cache full -> out_of_range.
    KVCache tiny = m.new_cache(1);
    cs.begin();
    m.encode_decode(cs, tiny, 1, nullptr);
    CHECK_THROWS(m.encode_decode(cs, tiny, 2, nullptr));
    cs.submit_and_wait();
}
