// Byte-level BPE tokenizer (tiktoken-compatible), loaded from tokenizer.json.
// gpt-oss uses the o200k_harmony vocabulary: 199 998 ordinary tokens plus
// special tokens in the 199 998..201 087 range (ids without a name in
// tokenizer.json are "<|reserved_N|>", up to config.json's vocab_size).
//
// Implementation (src/tokenizer/tokenizer.cpp): hand-written o200k
// pre-tokenizer over UTF-8 code points (Unicode category tables generated by
// scripts/gen_unicode_tables.py), then tiktoken-style rank-based BPE. Output
// is id-for-id identical to tiktoken's o200k_harmony
// (tests/data/tokenizer_vectors.json). Thread-safe.
#pragma once

#include <cstdint>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace coral {

class Tokenizer {
public:
    static std::unique_ptr<Tokenizer> load(const std::string& model_dir);  // throws
    virtual ~Tokenizer() = default;

    // Encode UTF-8 text. Special-token strings in `text` are treated as plain
    // text unless `allow_special` is set (the Harmony renderer adds specials
    // by id, never by string, so user input can never inject control tokens).
    virtual std::vector<int32_t> encode(std::string_view text, bool allow_special = false) const = 0;

    // Decode ids to UTF-8. Invalid sequences are replaced with U+FFFD.
    virtual std::string decode(std::span<const int32_t> ids) const = 0;

    // Raw bytes of one token (may be a partial UTF-8 sequence). Streaming
    // decoders accumulate these until a complete code point is available.
    virtual std::string_view token_bytes(int32_t id) const = 0;

    // Id of a special token such as "<|start|>", or -1 if unknown.
    virtual int32_t special(std::string_view name) const = 0;

    virtual size_t vocab_size() const = 0;
};

// Accumulates token bytes and emits only complete UTF-8 code points.
class Utf8Streamer {
public:
    // Returns the printable text now available (possibly empty).
    std::string push(std::string_view bytes);
    std::string flush();  // remaining bytes (invalid tail replaced by U+FFFD)
private:
    std::string pending_;
};

} // namespace coral
