#!/usr/bin/env python3
"""
Generate src/tokenizer/unicode_tables.h: compact Unicode general-category
ranges used by the hand-written o200k pre-tokenizer.

Dev tooling only; the generated header is committed so the C++ build never
needs Python.

    uv run --python 3.13 python3 scripts/gen_unicode_tables.py

Categories kept (everything else is "other"):
    1 Lu  2 Ll  3 Lt  4 Lm  5 Lo  6 M (Mn|Mc|Me)  7 N (Nd|Nl|No)
White_Space is small and hardcoded in the tokenizer.
"""
import os
import sys
import unicodedata

CAT = {"Lu": 1, "Ll": 2, "Lt": 3, "Lm": 4, "Lo": 5,
       "Mn": 6, "Mc": 6, "Me": 6, "Nd": 7, "Nl": 7, "No": 7}


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "src", "tokenizer", "unicode_tables.h")
    ranges = []  # [lo, hi, cat]
    for cp in range(0x110000):
        c = CAT.get(unicodedata.category(chr(cp)), 0)
        if c == 0:
            continue
        if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == c:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, c])
    lines = [
        "// GENERATED by scripts/gen_unicode_tables.py -- do not edit.",
        f"// Unicode {unicodedata.unidata_version} general categories, {len(ranges)} ranges.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace coral::unicode {",
        "",
        "enum Cat : uint8_t { kOther = 0, kLu = 1, kLl = 2, kLt = 3, kLm = 4, kLo = 5, kM = 6, kN = 7 };",
        "",
        "struct CatRange { uint32_t lo, hi; uint8_t cat; };",
        "",
        f"inline constexpr const char* kUnicodeVersion = \"{unicodedata.unidata_version}\";",
        f"inline constexpr uint32_t kCatRangeCount = {len(ranges)};",
        "inline constexpr CatRange kCatRanges[] = {",
    ]
    row = []
    for lo, hi, c in ranges:
        row.append(f"{{0x{lo:X},0x{hi:X},{c}}}")
        if len(row) == 6:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row) + ",")
    lines += ["};", "", "} // namespace coral::unicode", ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(ranges)} ranges (Unicode {unicodedata.unidata_version})", file=sys.stderr)


if __name__ == "__main__":
    main()
