// Build-time tool: concatenates Metal Shading Language sources into a C++
// include file so the engine can compile them at runtime with no external
// files and no Metal Toolchain dependency.
//
// Usage: embed_shaders <out.inc> <file.h|file.metal>...
//
// Files ending in .h are treated as headers and emitted first (in argument
// order) so that every .metal file may rely on them. The output defines:
//
//   namespace coral::shaders {
//     extern const char* const kSource;   // full MSL translation unit
//     extern const char* const kFiles[];  // names, for diagnostics
//     extern const unsigned    kFileCount;
//   }
//
// `#include "..."` lines inside the kernels are stripped because the headers
// are inlined; the runtime compiler has no include path.

#include <cstdio>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

static std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) { std::cerr << "embed_shaders: cannot read " << path << "\n"; std::exit(1); }
    std::stringstream ss; ss << in.rdbuf();
    return ss.str();
}

static std::string base_name(const std::string& p) {
    auto i = p.find_last_of('/');
    return i == std::string::npos ? p : p.substr(i + 1);
}

static bool ends_with(const std::string& s, const std::string& suf) {
    return s.size() >= suf.size() && s.compare(s.size() - suf.size(), suf.size(), suf) == 0;
}

// Emit as a raw string literal chunked so no single literal exceeds
// compiler limits; strip local #include lines.
static void emit_source(std::ostream& out, const std::string& name, const std::string& src) {
    out << "// ---- " << name << " ----\n";
    out << "\"#line 1 \\\"" << name << "\\\"\\n\"\n";
    std::istringstream lines(src);
    std::string line;
    while (std::getline(lines, line)) {
        if (line.rfind("#include \"", 0) == 0) { out << "\"\\n\"\n"; continue; }
        out << "\"";
        for (char c : line) {
            switch (c) {
                case '\\': out << "\\\\"; break;
                case '"':  out << "\\\""; break;
                case '\r': break;
                default:   out << c;
            }
        }
        out << "\\n\"\n";
    }
}

int main(int argc, char** argv) {
    if (argc < 3) { std::cerr << "usage: embed_shaders <out.inc> <sources...>\n"; return 1; }
    std::vector<std::string> headers, kernels;
    for (int i = 2; i < argc; ++i) (ends_with(argv[i], ".h") ? headers : kernels).push_back(argv[i]);

    std::ostringstream out;
    out << "// Generated by tools/embed_shaders.cpp. Do not edit.\n";
    out << "#pragma once\n#include <cstddef>\nnamespace coral::shaders {\n";
    out << "inline const char* const kSource =\n";
    for (auto& h : headers) emit_source(out, base_name(h), read_file(h));
    for (auto& k : kernels) emit_source(out, base_name(k), read_file(k));
    out << ";\n";
    out << "inline const char* const kFiles[] = {";
    for (auto& h : headers) out << "\"" << base_name(h) << "\",";
    for (auto& k : kernels) out << "\"" << base_name(k) << "\",";
    out << "};\n";
    out << "inline constexpr unsigned kFileCount = " << (headers.size() + kernels.size()) << ";\n";
    out << "} // namespace coral::shaders\n";

    // Only rewrite when changed, to keep incremental builds quiet.
    std::string next = out.str();
    std::ifstream cur(argv[1], std::ios::binary);
    if (cur) { std::stringstream ss; ss << cur.rdbuf(); if (ss.str() == next) return 0; }
    std::ofstream o(argv[1], std::ios::binary);
    o << next;
    return o ? 0 : 1;
}
